<?php

namespace Database\Seeders;

use App\Models\Employee;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    public function run()
    {
        $employees = [
            ['location_id'=>'999','name'           => 'Donald Cranston',],
            ['location_id'=>'999','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("LYNN CRANSTON")))),],
            ['location_id'=>'999','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("MELISSA KUNTZ")))),],
            ['location_id'=>'999','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("KAYLA BACHMEIER")))),],
            ['location_id'=>'999','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("KELLY SEITZ")))),],
            ['location_id'=>'999','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("PAUL OGDEN")))),],
            ['location_id'=>'999','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("TAMMY GRUE")))),],
            ['location_id'=>'999','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("BRAD WINSOR")))),],
            ['location_id'=>'999','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("Paul CLEWES")))),],
            ['location_id'=>'999','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("NICOLE SUTHERLAND")))),],
            ['location_id'=>'999','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("SHELLEY CHAMPION")))),],
            ['location_id'=>'999','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("MICHELLE WELLS")))),],
            ['location_id'=>'999','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("ANNETTE MATERI")))),],
            ['location_id'=>'999','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("LAURA HILLIS")))),],
            ['location_id'=>'999','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("CECILE SEEBECK")))),],
            ['location_id'=>'999','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("BRANDI PEDERSON")))),],
            ['location_id'=>'998','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("SCOTT PHINNEY")))),],
            ['location_id'=>'998','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("DARCY GOERTZEN")))),],
            ['location_id'=>'998','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("Kevin Elderkin")))),],
            ['location_id'=>'998','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("Janiece Richards")))),],
            ['location_id'=>'998','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("JEANETTE MACAULAY")))),],
            ['location_id'=>'998','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("SANDRA LOFGREN")))),],
            ['location_id'=>'998','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("DEVIE MAIER")))),],
            ['location_id'=>'998','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("VALERIE LEMNA")))),],
            ['location_id'=>'997','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("KIM MARSHALL")))),],
            ['location_id'=>'997','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("DONNELLY GRAD")))),],
            ['location_id'=>'997','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("ROSE WEBSTER")))),],
            ['location_id'=>'997','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("STEPHANIE ULRICHSEN")))),],
            ['location_id'=>'997','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("SANDRA NEUFELD")))),],
            ['location_id'=>'997','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("DEANNA THOMPSON")))),],
            ['location_id'=>'997','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("KATHY TETLOCK-CORVINUS")))),],
            ['location_id'=>'997','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("JIM GRAD")))),],
            ['location_id'=>'997','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("DEBORAH KEETLEY")))),],
            ['location_id'=>'997','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("PAT WILSON")))),],
            ['location_id'=>'997','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("TARA WASYLUK")))),],
            ['location_id'=>'997','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("LYNN FAUSER")))),],
            ['location_id'=>'997','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("MARCIA CLEMENT")))),],
            ['location_id'=>'997','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("GERDA	DE LANGE")))),],
            ['location_id'=>'997','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("SHERI LYNN BRUSKY")))),],
            ['location_id'=>'997','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("RENA MARIE BROWN")))),],
            ['location_id'=>'997','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("DEBRA BUECKERT")))),],
            ['location_id'=>'1','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("JENNIFER MCKENZIE")))),],
            ['location_id'=>'1','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("MICHELLE CRESSMAN")))),],
            ['location_id'=>'1','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("BERNICE	PEACOCK")))),],
            ['location_id'=>'1','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("CHRISTINA DAWN MILLS")))),],
            ['location_id'=>'1','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("MICHELLE MENZIES")))),],
            ['location_id'=>'1','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("ZOE 	MUDRACK")))),],
            ['location_id'=>'1','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("LORNA	FAVEL")))),],
            ['location_id'=>'1','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("Darcy 	Wedrick")))),],
            ['location_id'=>'1','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("HEAVEN 	CARLTON")))),],
            ['location_id'=>'1','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("KRISTEN 	RESENER")))),],
            ['location_id'=>'1','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("CELESTE 	HUNTER")))),],
            ['location_id'=>'1','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("BROOKLYN 	DAVIDSON")))),],
            ['location_id'=>'1','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("Jace 	LEVEQUE")))),],
            ['location_id'=>'1','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("Eileigh 	HARRIS-MCGHEE")))),],
            ['location_id'=>'1','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("JOLENE 	YANKE SHORT")))),],
            ['location_id'=>'1','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("ALEXA 	RUDE")))),],
            ['location_id'=>'1','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("CAITLIN 	CAMPBELL")))),],
            ['location_id'=>'1','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("LIELT 	SAMKET YESHIGETA")))),],
            ['location_id'=>'1','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("CHARLI	DAVIDSON")))),],
            ['location_id'=>'3','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("AMBER 	LAVOIE")))),],
            ['location_id'=>'3','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("DIANE 	ERICHSEN")))),],
            ['location_id'=>'3','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("CARLA 	MACKENZIE")))),],
            ['location_id'=>'3','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("CHRISTINE 	BARNES")))),],
            ['location_id'=>'3','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("CLEO	TETTEH")))),],
            ['location_id'=>'3','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("RILEY	SUTHERLAND")))),],
            ['location_id'=>'3','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("SALLY	BUSBY")))),],
            ['location_id'=>'3','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("CHEY-ANNE 	GILLESPIE")))),],
            ['location_id'=>'3','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("CRYSTAL 	GREENWALL")))),],
            ['location_id'=>'3','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("HAROLD	JACOBSON")))),],
            ['location_id'=>'3','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("ELIZABETH 	BAKER")))),],
            ['location_id'=>'3','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("TONI-LYNN 	NOBBS")))),],
            ['location_id'=>'3','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("Hope	Forslund-Clark")))),],
            ['location_id'=>'3','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("NEIL ALLAN JR.	YOUNG")))),],
            ['location_id'=>'3','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("TINA	JACKSON")))),],
            ['location_id'=>'3','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("SHAUN	KUHL")))),],
            ['location_id'=>'45','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("SHELBY 	BIANIC")))),],
            ['location_id'=>'45','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("YVONNE 	ROBINSON")))),],
            ['location_id'=>'45','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("LEANNE SUSAN	WALTER")))),],
            ['location_id'=>'45','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("JODY 	MCDOUGALL")))),],
            ['location_id'=>'45','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("ELIZABETH 	SEMENIUK")))),],
            ['location_id'=>'45','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("GRACE 	PEREIRA")))),],
            ['location_id'=>'45','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("Nola	Smith")))),],
            ['location_id'=>'44','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("DANIEL	FITZPATRICK")))),],
            ['location_id'=>'44','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("CONSTANZA 	COFRE ESPINOZA")))),],
            ['location_id'=>'44','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("JARED 	SKIRROW")))),],
            ['location_id'=>'44','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("BENJAMIN 	BRONSCH")))),],
            ['location_id'=>'44','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("CRYSTAL 	PILOTTE")))),],
            ['location_id'=>'44','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("JULIE 	ANGUS")))),],
            ['location_id'=>'44','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("KAYLA CRYSTAL	DESROSIERS")))),],
            ['location_id'=>'44','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("MARIBEL 	SORIANO")))),],
            ['location_id'=>'44','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("CINDY 	KELLY")))),],
            ['location_id'=>'44','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("ANNETTE 	BRONSCH")))),],
            ['location_id'=>'44','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("IZABELA 	VOJSOVICOVA")))),],
            ['location_id'=>'44','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("MAYA 	SESHIA")))),],
            ['location_id'=>'5','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("JEROME 	KOEBEL")))),],
            ['location_id'=>'5','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("MARLENE 	MOULD")))),],
            ['location_id'=>'5','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("YSALINE	DEPLASSE")))),],
            ['location_id'=>'5','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("JENNA 	DAVY")))),],
            ['location_id'=>'5','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("DARLA 	ENDICOTT")))),],
            ['location_id'=>'5','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("ELIJAH	NICHVALODOFF")))),],
            ['location_id'=>'47','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("MARIAH 	PENNER")))),],
            ['location_id'=>'47','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("TANIA 	ZACHARIAS")))),],
            ['location_id'=>'47','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("BARBARA	McCUAIG")))),],
            ['location_id'=>'47','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("BECKY 	THEISE")))),],
            ['location_id'=>'47','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("CASSANDRA 	BLYTH")))),],
            ['location_id'=>'47','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("ESTHER 	RATZLAFF")))),],
            ['location_id'=>'47','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("HALEY	FORFAR")))),],
            ['location_id'=>'48','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("MONTANA	KYLIUK")))),],
            ['location_id'=>'48','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("HAILEY 	LAFFERTY")))),],
            ['location_id'=>'48','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("JENNIFER 	LENHART")))),],
            ['location_id'=>'48','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("Leah 	Haas")))),],
            ['location_id'=>'48','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("DELPHINE 	MARYNIAK")))),],
            ['location_id'=>'48','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("RENAE 	BROOMAN")))),],
            ['location_id'=>'38','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("ALISON 	REYNOLDS")))),],
            ['location_id'=>'38','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("Nicole Dawn	Toren")))),],
            ['location_id'=>'38','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("LAURA 	PATON")))),],
            ['location_id'=>'38','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("AFTON 	MCELROY")))),],
            ['location_id'=>'38','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("MARGARET 	BOWEN")))),],
            ['location_id'=>'38','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("MICHAEL 	CAMPBELL")))),],
            ['location_id'=>'38','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("CARLEENA 	YATES")))),],
            ['location_id'=>'38','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("REBECCA 	MEISL")))),],
            ['location_id'=>'38','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("LINDA	FLOREN")))),],
            ['location_id'=>'38','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("Asia	Grant-Eshleman")))),],
            ['location_id'=>'38','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("CATHIE	WINTER")))),],
            ['location_id'=>'28','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("JONATHAN	BOWLEY")))),],
            ['location_id'=>'28','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("ALETHEIA 	CHACONAS")))),],
            ['location_id'=>'28','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("RIKKE 	LIISBERG-LARSEN")))),],
            ['location_id'=>'28','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("SAGE 	DUGUAY")))),],
            ['location_id'=>'28','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("Cassidy 	STAINTON")))),],
            ['location_id'=>'28','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("LYNDSEY 	HUSSEY")))),],
            ['location_id'=>'28','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("JASON	PATIENCE")))),],
            ['location_id'=>'10','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("RANDALL 	SMITH")))),],
            ['location_id'=>'10','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("MINEKO 	STRUEBY")))),],
            ['location_id'=>'10','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("MARNIE 	SOUTER")))),],
            ['location_id'=>'10','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("RACHEL 	BRAND")))),],
            ['location_id'=>'10','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("VANESSA 	PALABRICA")))),],
            ['location_id'=>'10','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("ELAINE 	GRAHAM")))),],
            ['location_id'=>'10','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("AMROELEN 	HERRERA")))),],
            ['location_id'=>'50','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("SHELLEY	JOHNSON")))),],
            ['location_id'=>'50','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("CHRISTOPHER 	JORGENSEN")))),],
            ['location_id'=>'50','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("Chandra 	Baeuchle")))),],
            ['location_id'=>'50','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("DAYNA 	GAERTNER")))),],
            ['location_id'=>'50','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("DANIELLE 	SABOURIN")))),],
            ['location_id'=>'50','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("Shelley 	Carefoot")))),],
            ['location_id'=>'50','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("HOLLY 	REDDIN")))),],
            ['location_id'=>'50','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("EDDIE 	GANUELAS")))),],
            ['location_id'=>'6','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("DAN 	MCINTYRE")))),],
            ['location_id'=>'6','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("FRANCES	POPE")))),],
            ['location_id'=>'6','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("HEATHER 	STRAIN")))),],
            ['location_id'=>'6','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("HAIDI 	NAVARRO")))),],
            ['location_id'=>'6','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("LORI 	BORAU")))),],
            ['location_id'=>'6','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("KEN 	LOWRY")))),],
            ['location_id'=>'6','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("Hannah 	Duda")))),],
            ['location_id'=>'6','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("TALIA 	ASHCROFT")))),],
            ['location_id'=>'6','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("ALICE 	JONES")))),],
            ['location_id'=>'6','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("JUDY 	SEBERG")))),],
            ['location_id'=>'6','name'           => preg_replace('!\s+!', ' ', (ucwords(strtolower("KEESHA 	HOLT")))),],

        ];
        Employee::insert($employees);
    }
}
