<?php

namespace Database\Seeders;

use App\Models\Employee;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    public function run()
    {
        $employees = [
            ['location_id'=>'999','name'           => 'Donald Cranston',],
            ['location_id'=>'999','name'           => ucwords(strtolower("LYNN CRANSTON")),],
            ['location_id'=>'999','name'           => ucwords(strtolower("MELISSA KUNTZ")),],
            ['location_id'=>'999','name'           => ucwords(strtolower("KAYLA BACHMEIER")),],
            ['location_id'=>'999','name'           => ucwords(strtolower("KELLY SEITZ")),],
            ['location_id'=>'999','name'           => ucwords(strtolower("PAUL OGDEN")),],
            ['location_id'=>'999','name'           => ucwords(strtolower("TAMMY GRUE")),],
            ['location_id'=>'999','name'           => ucwords(strtolower("BRAD WINSOR")),],
            ['location_id'=>'999','name'           => ucwords(strtolower("Paul CLEWES")),],
            ['location_id'=>'999','name'           => ucwords(strtolower("NICOLE SUTHERLAND")),],
            ['location_id'=>'999','name'           => ucwords(strtolower("SHELLEY CHAMPION")),],
            ['location_id'=>'999','name'           => ucwords(strtolower("MICHELLE WELLS")),],
            ['location_id'=>'999','name'           => ucwords(strtolower("ANNETTE MATERI")),],
            ['location_id'=>'999','name'           => ucwords(strtolower("LAURA HILLIS")),],
            ['location_id'=>'999','name'           => ucwords(strtolower("CECILE SEEBECK")),],
            ['location_id'=>'999','name'           => ucwords(strtolower("BRANDI PEDERSON")),],
            ['location_id'=>'998','name'           => ucwords(strtolower("SCOTT PHINNEY")),],
            ['location_id'=>'998','name'           => ucwords(strtolower("DARCY GOERTZEN")),],
            ['location_id'=>'998','name'           => ucwords(strtolower("Kevin Elderkin")),],
            ['location_id'=>'998','name'           => ucwords(strtolower("Janiece Richards")),],
            ['location_id'=>'998','name'           => ucwords(strtolower("JEANETTE MACAULAY")),],
            ['location_id'=>'998','name'           => ucwords(strtolower("SANDRA	LOFGREN")),],
            ['location_id'=>'998','name'           => ucwords(strtolower("DEVIE	MAIER")),],
            ['location_id'=>'998','name'           => ucwords(strtolower("VALERIE LEMNA")),],
            ['location_id'=>'997','name'           => ucwords(strtolower("KIM MARSHALL")),],
            ['location_id'=>'997','name'           => ucwords(strtolower("DONNELLY GRAD")),],
            ['location_id'=>'997','name'           => ucwords(strtolower("ROSE WEBSTER")),],
            ['location_id'=>'997','name'           => ucwords(strtolower("STEPHANIE ULRICHSEN")),],
            ['location_id'=>'997','name'           => ucwords(strtolower("SANDRA NEUFELD")),],
            ['location_id'=>'997','name'           => ucwords(strtolower("DEANNA	THOMPSON")),],
            ['location_id'=>'997','name'           => ucwords(strtolower("KATHY TETLOCK-CORVINUS")),],
            ['location_id'=>'997','name'           => ucwords(strtolower("JIM 	GRAD")),],
            ['location_id'=>'997','name'           => ucwords(strtolower("DEBORAH 	KEETLEY")),],
            ['location_id'=>'997','name'           => ucwords(strtolower("PAT 	WILSON")),],
            ['location_id'=>'997','name'           => ucwords(strtolower("TARA 	WASYLUK")),],
            ['location_id'=>'997','name'           => ucwords(strtolower("LYNN 	FAUSER")),],
            ['location_id'=>'997','name'           => ucwords(strtolower("MARCIA 	CLEMENT")),],
            ['location_id'=>'997','name'           => ucwords(strtolower("GERDA 	DE LANGE")),],
            ['location_id'=>'997','name'           => ucwords(strtolower("SHERI LYNN	BRUSKY")),],
            ['location_id'=>'997','name'           => ucwords(strtolower("RENA MARIE	BROWN")),],
            ['location_id'=>'997','name'           => ucwords(strtolower("DEBRA 	BUECKERT")),],
            ['location_id'=>'1','name'           => ucwords(strtolower("JENNIFER 	MCKENZIE")),],
            ['location_id'=>'1','name'           => ucwords(strtolower("MICHELLE 	CRESSMAN")),],
            ['location_id'=>'1','name'           => ucwords(strtolower("BERNICE 	PEACOCK")),],
            ['location_id'=>'1','name'           => ucwords(strtolower("CHRISTINA DAWN	MILLS")),],
            ['location_id'=>'1','name'           => ucwords(strtolower("MICHELLE 	MENZIES")),],
            ['location_id'=>'1','name'           => ucwords(strtolower("ZOE 	MUDRACK")),],
            ['location_id'=>'1','name'           => ucwords(strtolower("LORNA	FAVEL")),],
            ['location_id'=>'1','name'           => ucwords(strtolower("Darcy 	Wedrick")),],
            ['location_id'=>'1','name'           => ucwords(strtolower("HEAVEN 	CARLTON")),],
            ['location_id'=>'1','name'           => ucwords(strtolower("KRISTEN 	RESENER")),],
            ['location_id'=>'1','name'           => ucwords(strtolower("CELESTE 	HUNTER")),],
            ['location_id'=>'1','name'           => ucwords(strtolower("BROOKLYN 	DAVIDSON")),],
            ['location_id'=>'1','name'           => ucwords(strtolower("Jace 	LEVEQUE")),],
            ['location_id'=>'1','name'           => ucwords(strtolower("Eileigh 	HARRIS-MCGHEE")),],
            ['location_id'=>'1','name'           => ucwords(strtolower("JOLENE 	YANKE SHORT")),],
            ['location_id'=>'1','name'           => ucwords(strtolower("ALEXA 	RUDE")),],
            ['location_id'=>'1','name'           => ucwords(strtolower("CAITLIN 	CAMPBELL")),],
            ['location_id'=>'1','name'           => ucwords(strtolower("LIELT 	SAMKET YESHIGETA")),],
            ['location_id'=>'1','name'           => ucwords(strtolower("CHARLI	DAVIDSON")),],
            ['location_id'=>'3','name'           => ucwords(strtolower("AMBER 	LAVOIE")),],
            ['location_id'=>'3','name'           => ucwords(strtolower("DIANE 	ERICHSEN")),],
            ['location_id'=>'3','name'           => ucwords(strtolower("CARLA 	MACKENZIE")),],
            ['location_id'=>'3','name'           => ucwords(strtolower("CHRISTINE 	BARNES")),],
            ['location_id'=>'3','name'           => ucwords(strtolower("CLEO	TETTEH")),],
            ['location_id'=>'3','name'           => ucwords(strtolower("RILEY	SUTHERLAND")),],
            ['location_id'=>'3','name'           => ucwords(strtolower("SALLY	BUSBY")),],
            ['location_id'=>'3','name'           => ucwords(strtolower("CHEY-ANNE 	GILLESPIE")),],
            ['location_id'=>'3','name'           => ucwords(strtolower("CRYSTAL 	GREENWALL")),],
            ['location_id'=>'3','name'           => ucwords(strtolower("HAROLD	JACOBSON")),],
            ['location_id'=>'3','name'           => ucwords(strtolower("ELIZABETH 	BAKER")),],
            ['location_id'=>'3','name'           => ucwords(strtolower("TONI-LYNN 	NOBBS")),],
            ['location_id'=>'3','name'           => ucwords(strtolower("Hope	Forslund-Clark")),],
            ['location_id'=>'3','name'           => ucwords(strtolower("NEIL ALLAN JR.	YOUNG")),],
            ['location_id'=>'3','name'           => ucwords(strtolower("TINA	JACKSON")),],
            ['location_id'=>'3','name'           => ucwords(strtolower("SHAUN	KUHL")),],
            ['location_id'=>'45','name'           => ucwords(strtolower("SHELBY 	BIANIC")),],
            ['location_id'=>'45','name'           => ucwords(strtolower("YVONNE 	ROBINSON")),],
            ['location_id'=>'45','name'           => ucwords(strtolower("LEANNE SUSAN	WALTER")),],
            ['location_id'=>'45','name'           => ucwords(strtolower("JODY 	MCDOUGALL")),],
            ['location_id'=>'45','name'           => ucwords(strtolower("ELIZABETH 	SEMENIUK")),],
            ['location_id'=>'45','name'           => ucwords(strtolower("GRACE 	PEREIRA")),],
            ['location_id'=>'45','name'           => ucwords(strtolower("Nola	Smith")),],
            ['location_id'=>'44','name'           => ucwords(strtolower("DANIEL	FITZPATRICK")),],
            ['location_id'=>'44','name'           => ucwords(strtolower("CONSTANZA 	COFRE ESPINOZA")),],
            ['location_id'=>'44','name'           => ucwords(strtolower("JARED 	SKIRROW")),],
            ['location_id'=>'44','name'           => ucwords(strtolower("BENJAMIN 	BRONSCH")),],
            ['location_id'=>'44','name'           => ucwords(strtolower("CRYSTAL 	PILOTTE")),],
            ['location_id'=>'44','name'           => ucwords(strtolower("JULIE 	ANGUS")),],
            ['location_id'=>'44','name'           => ucwords(strtolower("KAYLA CRYSTAL	DESROSIERS")),],
            ['location_id'=>'44','name'           => ucwords(strtolower("MARIBEL 	SORIANO")),],
            ['location_id'=>'44','name'           => ucwords(strtolower("CINDY 	KELLY")),],
            ['location_id'=>'44','name'           => ucwords(strtolower("ANNETTE 	BRONSCH")),],
            ['location_id'=>'44','name'           => ucwords(strtolower("IZABELA 	VOJSOVICOVA")),],
            ['location_id'=>'44','name'           => ucwords(strtolower("MAYA 	SESHIA")),],
            ['location_id'=>'5','name'           => ucwords(strtolower("JEROME 	KOEBEL")),],
            ['location_id'=>'5','name'           => ucwords(strtolower("MARLENE 	MOULD")),],
            ['location_id'=>'5','name'           => ucwords(strtolower("YSALINE	DEPLASSE")),],
            ['location_id'=>'5','name'           => ucwords(strtolower("JENNA 	DAVY")),],
            ['location_id'=>'5','name'           => ucwords(strtolower("DARLA 	ENDICOTT")),],
            ['location_id'=>'5','name'           => ucwords(strtolower("ELIJAH	NICHVALODOFF")),],
            ['location_id'=>'47','name'           => ucwords(strtolower("MARIAH 	PENNER")),],
            ['location_id'=>'47','name'           => ucwords(strtolower("TANIA 	ZACHARIAS")),],
            ['location_id'=>'47','name'           => ucwords(strtolower("BARBARA	McCUAIG")),],
            ['location_id'=>'47','name'           => ucwords(strtolower("BECKY 	THEISE")),],
            ['location_id'=>'47','name'           => ucwords(strtolower("CASSANDRA 	BLYTH")),],
            ['location_id'=>'47','name'           => ucwords(strtolower("ESTHER 	RATZLAFF")),],
            ['location_id'=>'47','name'           => ucwords(strtolower("HALEY	FORFAR")),],
            ['location_id'=>'48','name'           => ucwords(strtolower("MONTANA	KYLIUK")),],
            ['location_id'=>'48','name'           => ucwords(strtolower("HAILEY 	LAFFERTY")),],
            ['location_id'=>'48','name'           => ucwords(strtolower("JENNIFER 	LENHART")),],
            ['location_id'=>'48','name'           => ucwords(strtolower("Leah 	Haas")),],
            ['location_id'=>'48','name'           => ucwords(strtolower("DELPHINE 	MARYNIAK")),],
            ['location_id'=>'48','name'           => ucwords(strtolower("RENAE 	BROOMAN")),],
            ['location_id'=>'38','name'           => ucwords(strtolower("ALISON 	REYNOLDS")),],
            ['location_id'=>'38','name'           => ucwords(strtolower("Nicole Dawn	Toren")),],
            ['location_id'=>'38','name'           => ucwords(strtolower("LAURA 	PATON")),],
            ['location_id'=>'38','name'           => ucwords(strtolower("AFTON 	MCELROY")),],
            ['location_id'=>'38','name'           => ucwords(strtolower("MARGARET 	BOWEN")),],
            ['location_id'=>'38','name'           => ucwords(strtolower("MICHAEL 	CAMPBELL")),],
            ['location_id'=>'38','name'           => ucwords(strtolower("CARLEENA 	YATES")),],
            ['location_id'=>'38','name'           => ucwords(strtolower("REBECCA 	MEISL")),],
            ['location_id'=>'38','name'           => ucwords(strtolower("LINDA	FLOREN")),],
            ['location_id'=>'38','name'           => ucwords(strtolower("Asia	Grant-Eshleman")),],
            ['location_id'=>'38','name'           => ucwords(strtolower("CATHIE	WINTER")),],
            ['location_id'=>'28','name'           => ucwords(strtolower("JONATHAN	BOWLEY")),],
            ['location_id'=>'28','name'           => ucwords(strtolower("ALETHEIA 	CHACONAS")),],
            ['location_id'=>'28','name'           => ucwords(strtolower("RIKKE 	LIISBERG-LARSEN")),],
            ['location_id'=>'28','name'           => ucwords(strtolower("SAGE 	DUGUAY")),],
            ['location_id'=>'28','name'           => ucwords(strtolower("Cassidy 	STAINTON")),],
            ['location_id'=>'28','name'           => ucwords(strtolower("LYNDSEY 	HUSSEY")),],
            ['location_id'=>'28','name'           => ucwords(strtolower("JASON	PATIENCE")),],
            ['location_id'=>'10','name'           => ucwords(strtolower("RANDALL 	SMITH")),],
            ['location_id'=>'10','name'           => ucwords(strtolower("MINEKO 	STRUEBY")),],
            ['location_id'=>'10','name'           => ucwords(strtolower("MARNIE 	SOUTER")),],
            ['location_id'=>'10','name'           => ucwords(strtolower("RACHEL 	BRAND")),],
            ['location_id'=>'10','name'           => ucwords(strtolower("VANESSA 	PALABRICA")),],
            ['location_id'=>'10','name'           => ucwords(strtolower("ELAINE 	GRAHAM")),],
            ['location_id'=>'10','name'           => ucwords(strtolower("AMROELEN 	HERRERA")),],
            ['location_id'=>'50','name'           => ucwords(strtolower("SHELLEY	JOHNSON")),],
            ['location_id'=>'50','name'           => ucwords(strtolower("CHRISTOPHER 	JORGENSEN")),],
            ['location_id'=>'50','name'           => ucwords(strtolower("Chandra 	Baeuchle")),],
            ['location_id'=>'50','name'           => ucwords(strtolower("DAYNA 	GAERTNER")),],
            ['location_id'=>'50','name'           => ucwords(strtolower("DANIELLE 	SABOURIN")),],
            ['location_id'=>'50','name'           => ucwords(strtolower("Shelley 	Carefoot")),],
            ['location_id'=>'50','name'           => ucwords(strtolower("HOLLY 	REDDIN")),],
            ['location_id'=>'50','name'           => ucwords(strtolower("EDDIE 	GANUELAS")),],
            ['location_id'=>'6','name'           => ucwords(strtolower("DAN 	MCINTYRE")),],
            ['location_id'=>'6','name'           => ucwords(strtolower("FRANCES	POPE")),],
            ['location_id'=>'6','name'           => ucwords(strtolower("HEATHER 	STRAIN")),],
            ['location_id'=>'6','name'           => ucwords(strtolower("HAIDI 	NAVARRO")),],
            ['location_id'=>'6','name'           => ucwords(strtolower("LORI 	BORAU")),],
            ['location_id'=>'6','name'           => ucwords(strtolower("KEN 	LOWRY")),],
            ['location_id'=>'6','name'           => ucwords(strtolower("Hannah 	Duda")),],
            ['location_id'=>'6','name'           => ucwords(strtolower("TALIA 	ASHCROFT")),],
            ['location_id'=>'6','name'           => ucwords(strtolower("ALICE 	JONES")),],
            ['location_id'=>'6','name'           => ucwords(strtolower("JUDY 	SEBERG")),],
            ['location_id'=>'6','name'           => ucwords(strtolower("KEESHA 	HOLT")),],

        ];
        Employee::insert($employees);
    }
}
